FROM openjdk:15-jdk-alpine
LABEL maintainer krutikov@sheridancollege.ca
COPY target/CustomTattooDesign_MobileCRM-0.0.1-SNAPSHOT.jar ctdhelloworld.jar
ENTRYPOINT ["java","-jar","ctdhelloworld.jar"]
EXPOSE 4004
ENV capDBusername=setWhenCompiling  \
    capDBpassword=setWhenCompiling  \
	capDBhost=setWhenCompiling  \
	capDBdatabase=setWhenCompiling  \
	capDBport=setWhenCompiling  \
	capTestId=setWhenCompiling  \
	capTestId2=setWhenCompiling  \
	capTestUser=setWhenCompiling  \	
	capTestPassword=setWhenCompiling  \
	capTestUser2=setWhenCompiling  \	
	capTestPassword2=setWhenCompiling  \
	capTestSessionToken=setWhenCompiling  \
	capTestSessionToken2=setWhenCompiling  \
	capTestJobId=setWhenCompiling  \
	capTestJobId2=setWhenCompiling  \
	capTestJobExpectedSize=setWhenCompiling  \
	capTestJobExpectedSize2=setWhenCompiling  \
	capTestMessagesExpectedSize=setWhenCompiling  \
	capTestMessagesExpectedSize2=setWhenCompiling  \
	capTestDesignId=setWhenCompiling \
	capTestDesignId2=setWhenCompiling \
	capTestImageName=setWhenCompiling \
	capTestImageName2=setWhenCompiling \
	capTestEncodedJobId=setWhenCompiling \
	capTestEncodedJobId2=setWhenCompiling \
	capAWSBucketName=setWhenCompiling \
	capAWSAccessKey=setWhenCompiling \
	capAWSSecretKey=setWhenCompiling \
	capAWSRegion=setWhenCompiling 